### ISSUE TITLE
Odd behavior in radiation heat transfer with GEOM

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11854]
The attached image is showing the wall temperature for two cases both using GEOM. In both cases the radiant heater and the panel are both GEOM objects with one of them rotated and the other aligned to the cartesian grid. The one on the left has the heater panel aligned and the sample rotated. The one on the right has the heater panel rotated (and gravity rotated) and the panel aligned to the cartesian grid. My expectation is that these two models should provide the same answer. However, there is a small patch in the left sample which heats significantly faster than the right near the top (blue arrow). There is also an odd artifact being produced on the panel in the left case (red arrow). I have attached the two input files.
 
![image](https://github.com/firemodels/fds/assets/17127980/995dcb54-eba3-40d0-a397-e60b64287442)

[radiant_panel_plywood_geom_rot.txt](https://github.com/firemodels/fds/files/11575422/radiant_panel_plywood_geom_rot.txt)
[radiant_panel_plywood_geom.txt](https://github.com/firemodels/fds/files/11575425/radiant_panel_plywood_geom.txt)

**Comment by johodges** [comment]
During the discussion earlier today we identified this is most likely due to the cut cell crossing two gas phase cells in the left model. Restarting these cases with CELL_BLOCK_IOR set to preserve the flat profile on the sample.

**Comment by marcosvanella** [comment]
Thank you Jon, I'm running these and will let you know what I find.

**Comment by johodges** [comment]
I checked back in on these cases today. We are still seeing the striations in the wall temperature from radiation after adding CELL_BLOCK_IOR to force the back side of the sample to snap to the grid.

![image](https://github.com/firemodels/fds/assets/17127980/6268e170-58cc-4fcb-a2b2-9ab3587
[radiant_panel_plywood_geom.txt](https://github.com/firemodels/fds/files/11625783/radiant_panel_plywood_geom.txt)
8154c)

**Comment by marcosvanella** [comment]
Update on this. I tested the radiation solver for cases with geometry boundary faces projected in default mode (snapping them to the cartesian face closer to their centroid in each direction) and also projecting them towards the gas phase. I made the radiant panel an obst to have the same source. 
The location of these projected cfaces affects radiative intensity soln and the incident heat flux we are computing. They will partially block the incoming rays on different places. Same with radiation emitted.
I'm running finer grid cases to compare.
- Default:
<img width="997" alt="Screenshot 2023-06-01 at 5 03 47 PM" src="https://github.com/firemodels/fds/assets/7450069/667167ad-b17e-4fa3-ae41-17b235cc40a9">

- Project out:
<img width="996" alt="Screenshot 2023-06-01 at 5 03 58 PM" src="https://github.com/firemodels/fds/assets/7450069/a02675b3-9d61-4ad6-80d0-67f9c2511da3">

**Comment by johodges** [comment]
Thanks for the update. It's a bit hard to tell from the figure but it looks to me like the CELL_BLOCK_IOR is not set in the project out case in your most recent communication (I see non-flat triangles on both side of the sample at different points). Am I misunderstanding what you changed in that model compared to the default?

I asked one of my staff to set up this model in Abaqus to benchmark the radiation distribution from its S2S radiation solver. I'll let you know how that compares tomorrow.

**Comment by johodges** [comment]
Here are the incident radiation predictions simulated by Abaqus.
![astme162_abaqus_s2s](https://github.com/firemodels/fds/assets/17127980/40ad8368-97dd-452d-8f5b-9e4f634e1527)

Here is the incident radiation I am seeing from FDS for the rotated geometry case (where the sample is aligned to the mesh). I am not sure why but the boundary data is not loading for me in smokeview right now (tried with the version bundled with 6.8 and with the nightly build).
![image](https://github.com/firemodels/fds/assets/17127980/ea56c70f-54ee-4476-8dcb-2ccce19f2faa)

**Comment by ericvmueller** [comment]
@johodges when you get a chance, try with the changes I just pushed and see if there is an improvement

**Comment by johodges** [comment]
Thanks for the update. I'm planning to start them in the morning assuming we have a clean firebot run with the other changes this week.

**Comment by johodges** [comment]
Results look promising with Eric's recent change for the cfaces. No striping visible in the lattimer 11 degree tilted wall case. I am planning to run the rest of the tilted cases and generate the validation plots. Our cluster is pretty backed up right now so it will probably be the weekend before I can get them running. I should have the results for us to look at in the next dev meeting.

![image](https://github.com/firemodels/fds/assets/17127980/88fcd90e-7dd0-4838-b2a1-c364f16939ff)

**Comment by RIO4FDS** [comment]
In my panels, I still see some striping.

![image](https://github.com/firemodels/fds/assets/12700159/8a610a54-b1bf-4c60-b16e-d714e3007bd6)

![image](https://github.com/firemodels/fds/assets/12700159/32e18bb8-ca2d-4c6c-b58f-b7c59734ec33)

I attached the smallest case I have.
[PNB_CYL10_TMP600_HTC0.txt](https://github.com/firemodels/fds/files/12753440/PNB_CYL10_TMP600_HTC0.txt)

**Comment by ericvmueller** [comment]
Okay - thanks for posting, will take a look

**Comment by johodges** [comment]
The striping is better in my cases as well, but there are artifacts present at the mesh boundaries. This is the case here: 
https://github.com/firemodels/fds/blob/master/Validation/Lattimer_Tilted_Wall/FDS_Input_Files/Lattimer_50_kW_11_degree.fds

![image](https://github.com/firemodels/fds/assets/17127980/e6b1347e-c2b7-4b22-8b06-a2b757fc56aa)

One of the cases is also crashing now. This is the case here: 
https://github.com/firemodels/fds/blob/master/Validation/Lattimer_Tilted_Wall/FDS_Input_Files/Lattimer_50_kW_23_degree.fds

![image](https://github.com/firemodels/fds/assets/17127980/ef87f4d4-5e3a-4a7b-9b49-017cad628bee)

**Comment by ericvmueller** [comment]
Just running a firebot to test some fixes that came up when looking into Julio's case (related to how face normals are assigned when split cells are blocked). If that goes through we can look at these next.

**Comment by ericvmueller** [comment]
@johodges I think your first issue isn't related to the GEOM, but rather that you have transient sources of radiation at/near the mesh boundaries and the fact that the FVM solution isn't iterated to ensure consistency across meshes.

Even in the 0-degree OBST case you can see inconsistency in the radiation field at the mesh boundary.
<img width="295" alt="image" src="https://github.com/firemodels/fds/assets/13366803/2fb1964c-3333-4214-b16b-9b47870cc803">


It does seem you can improve things by increasing how frequently the whole field is updated in each mesh. I set `ANGLE_INCREMENT=1` and `TIME_STEP_INCREMENT=1` and get the following for the 11 degree case. Obviously that slows down the calculation but maybe you can find a happy medium that gives the result you want.
<img width="281" alt="image" src="https://github.com/firemodels/fds/assets/13366803/d186f427-205f-4716-a880-a2fe93750d5f">


The second issue seems more likely to be GEOM related.

**Comment by ericvmueller** [comment]
@RIO4FDS for your case 2202c112652d2672563082f1f528d557d8a6c94b fixed an issue at the very edge of the panel where the flux was wrong because of cell blocking
![image](https://github.com/firemodels/fds/assets/13366803/2a4cb7d3-a175-48fa-936c-283ac310dec5)

Now it looks like this
![image](https://github.com/firemodels/fds/assets/13366803/a9e35e02-63c4-4216-b307-20ab8d2be44d)

...as for the stripes across the panel, I think this is related to having a relatively discrete source of radiation that decays rapidly with distance and a coarse grid resolution over which the field is resolved. 
As you can see above, the panel cuts through cells that are at different distances from the source, so those smaller cut cells which are further away are giving slightly lower fluxes at the boundary. If you shift your panel so it cuts right through the diagonal of your cells you shouldn't see the stripes. Alternatively you can increase the grid resolution and get a somewhat smoother solution:
![image](https://github.com/firemodels/fds/assets/13366803/d3f05341-4f6d-4cef-9e86-c9f7973cd613)

If you put devices across the surface these are the profiles of flux you get for the two grid resolutions. There is still some jitter at the higher resolution but the error is ~1% which is perhaps not so bad for such low heat fluxes.
![image](https://github.com/firemodels/fds/assets/13366803/f53c0c02-c8cb-4142-b29a-077e4faa5de6)

**Comment by RIO4FDS** [comment]
@ericvmueller thank you for the update.
I will follow your train of thoughts!

**Comment by johodges** [comment]
Thanks for the update. I'll get these kicked off.

**Comment by marcosvanella** [comment]
Jon given that Lattimer cases run without instabilities, can we close this?

**Comment by johodges** [comment]
Sounds good. Once I have a chance to add the cases to the validation guide after this release I will re-open or start a new issue if needed.
