### ISSUE TITLE
drag screen problem in smokewiev

### ISSUE THREAD

**Issue by Petr88** [firemodels/fds#3243]
Hi i have a problem with drag screen. I used drag screens with thickness by coordinates = 0 and these are located on borders between cells. When I run smokewiev I saw this...
Here pictures with plan of my building with slices files of velocity in time 0.0s / 0.7s / 1.1s / 1.4s / 3.3s / 4.3.s / 5.8s. You can see wierd values of velocity on drag screens. I dont understand why. Can you help? 

![t0 7](https://cloud.githubusercontent.com/assets/16324352/11846869/dcfadcd2-a41a-11e5-926a-be65fc1887c1.jpg)
![t0](https://cloud.githubusercontent.com/assets/16324352/11846868/dcf77ad8-a41a-11e5-9e29-dc466e48ca6c.jpg)
![t1 1](https://cloud.githubusercontent.com/assets/16324352/11846872/dd0050a4-a41a-11e5-9911-75aa07127e02.jpg)
![t1 4](https://cloud.githubusercontent.com/assets/16324352/11846873/dd01a86e-a41a-11e5-9fa5-1fb547324251.jpg)
![t3 3](https://cloud.githubusercontent.com/assets/16324352/11846870/dcfb48d4-a41a-11e5-95a4-d669b57278b9.jpg)
![t4 3](https://cloud.githubusercontent.com/assets/16324352/11846871/dd0098de-a41a-11e5-8f89-b071a8fb36ac.jpg)
![t5 8](https://cloud.githubusercontent.com/assets/16324352/11846874/dd12496c-a41a-11e5-81af-d3dbfe8c9ae7.jpg)
![t10](https://cloud.githubusercontent.com/assets/16324352/11846875/dd1a4158-a41a-11e5-87ec-ffa23ca5c72d.jpg)

**Comment by mcgratta** [comment]
Are you the one who posted a case on the Discussion Group? Why don't you post that case here. We cannot work with the images.

**Comment by Petr88** [comment]
I dont know how insert txt here.
Well, here is link to discussion group: https://groups.google.com/forum/?fromgroups=#!topic/fds-smv/mK3kEDUp18M 

and here is my simple test.There are 3 meshes. In every mesh is different location of screen. The highest mesh shows my problem with screen in smokewiev, if you use slice file temperature in plane z. I appreciate every idea.

&HEAD CHID='screen_drag_1',TITLE='screen drag pressure drop 2 m/s'/
&REAC ID = 'PROPANE',
      FUEL = 'PROPANE'
      C = 3.
      H = 8.
      SOOT_YIELD = 0.12 /
&MESH IJK=20,10,10,XB=0,2,0,1,0,1/
&MESH IJK=20,10,10,XB=0,2,0,1,1.1,2.1/
&MESH IJK=20,10,10,XB=0,2,0,1,2.2,3.2/

&TIME T_END=100./
&RADI RADIATION=.FALSE./

&VENT XB = 2.0,2.0, 0.0,1.0, 0.0,1, SURF_ID = 'OPEN'/
&VENT XB = 2.0,2.0, 0.0,1.0, 1.1,2.1, SURF_ID = 'OPEN'/
&VENT XB = 2.0,2.0, 0.0,1.0, 2.2,3.2, SURF_ID = 'OPEN'/

&SLCF PBY=0.5,QUANTITY='VELOCITY',VECTOR=.TRUE./
&SLCF PBY=0.5,QUANTITY='TEMPERATURE',VECTOR=.TRUE./
&SLCF PBZ=0.7,QUANTITY='VELOCITY',VECTOR=.TRUE./
&SLCF PBZ=1.8,QUANTITY='VELOCITY',VECTOR=.TRUE./
&SLCF PBZ=2.8,QUANTITY='VELOCITY',VECTOR=.TRUE./
&SLCF PBZ=0.7,QUANTITY='TEMPERATURE',VECTOR=.TRUE./
&SLCF PBZ=1.8,QUANTITY='TEMPERATURE',VECTOR=.TRUE./
&SLCF PBZ=2.8,QUANTITY='TEMPERATURE',VECTOR=.TRUE./
&SLCF PBY=0.5,QUANTITY='PRESSURE'/

&SURF ID='SCREEN',THICKNESS=0.001, GEOMETRY='CYLINDRICAL',MATL_ID='SCREEN'/
&MATL ID='SCREEN',DENSITY=2700.,CONDUCTIVITY=200,SPECIFIC_HEAT=0.9/

&PART DRAG_LAW='SCREEN',ID='SCREEN1',SURF_ID='SCREEN',FREE_AREA_FRACTION=0.7, STATIC=.TRUE.,ORIENTATION=1,0,0  /
&PART DRAG_LAW='SCREEN',ID='SCREEN2',SURF_ID='SCREEN',FREE_AREA_FRACTION=0.7, STATIC=.TRUE.,ORIENTATION=1,0,0  /
&PART DRAG_LAW='SCREEN',ID='SCREEN3',SURF_ID='SCREEN',FREE_AREA_FRACTION=0.7, STATIC=.TRUE.,ORIENTATION=1,0,0  /

&INIT N_PARTICLES_PER_CELL=1,CELL_CENTERED=.TRUE.,PART_ID='SCREEN1',XB=1.05,1.05,0.0,1.0,0.0,1.0/
&INIT N_PARTICLES_PER_CELL=1,CELL_CENTERED=.TRUE.,PART_ID='SCREEN2',XB=1.01,1.01,0.0,1.0,1.1,2.1/
&INIT N_PARTICLES_PER_CELL=1,CELL_CENTERED=.TRUE.,PART_ID='SCREEN3',XB=1.00,1.00,0.0,1.0,2.2,3.2/

&OBST XB = 0.0,0.2, 0.0,1.0, 0.0,0.10, SURF_ID = 'INERT', COLOR = 'FLESH' /
&VENT XB = 0.0,0.2, 0.0,1.0, 0.11,0.11, SURF_ID = 'FIRE', COLOR = 'FLESH' / 

&OBST XB = 0.0,0.2, 0.0,1.0, 1.1,1.20, SURF_ID = 'INERT', COLOR = 'FLESH' /
&VENT XB = 0.0,0.2, 0.0,1.0, 1.21,1.21, SURF_ID = 'FIRE', COLOR = 'FLESH' / 

&OBST XB = 0.0,0.2, 0.0,1.0, 2.2,2.30, SURF_ID = 'INERT', COLOR = 'FLESH' /
&VENT XB = 0.0,0.2, 0.0,1.0, 2.31,2.31, SURF_ID = 'FIRE', COLOR = 'FLESH' /  

&SURF ID = 'FIRE', HRRPUA = 50, RAMP_Q = 'fireramp' /
&RAMP ID = 'fireramp', T = 0.0,   F = 0.0 / ... 
&RAMP ID = 'fireramp', T = 0.4,  F = 0.01 /
&RAMP ID = 'fireramp', T = 0.8,  F = 1.00 /
&RAMP ID = 'fireramp', T = 0.9,  F = 1.00 /

**Comment by mcgratta** [comment]
I do not understand what the problem is. Why do you have combustion? You should just test to see if the screen produces the desired pressure drop when you blow air through the channel.

**Comment by Petr88** [comment]
In TITLE is wrong text. I use screens for simulation of a move of smoke and heat through thin sheets with free area (= 70 %)  during a fire .

**Comment by mcgratta** [comment]
What do you expect the results of your calculation to be? I do not understand what is wrong.

**Comment by Petr88** [comment]
Well, as you can see in pictures above. There are velocity in drag srceens. But it doesnt make any sence, because it is at first seconds of the simulation and a combustion doesnt start yet. I think that problem is a location of drag screens. Location is on borders between cells. 
So I post to you simple test with three meshes. In each of these meshes are different locations of drag screens. You have to show slice file of temperature (or velocity) in all meshes in plane z . After that you can see, that values of temperature (or velocity) in mesh 3 is unusuall.... like in pictures above. A hope you understand it.

**Comment by mcgratta** [comment]
This case demonstrates the problem

```
&HEAD CHID='screen_drag_1',TITLE='screen drag pressure drop 2 m/s'/
&MESH IJK=20,10,10,XB=0,2,0,1,0,1/
&MESH IJK=20,10,10,XB=0,2,0,1,1.1,2.1/
&TIME T_END=10./
&VENT MB='XMIN', SURF_ID = 'OPEN'/
&VENT MB='XMAX', SURF_ID = 'OPEN'/
&SLCF PBY=0.5,QUANTITY='VELOCITY',VECTOR=.TRUE. /
&SLCF PBY=0.5,QUANTITY='TEMPERATURE' /
&SLCF PBY=0.5,QUANTITY='PRESSURE' /
&SURF ID='SCREEN',THICKNESS=0.001, GEOMETRY='CYLINDRICAL',MATL_ID='SCREEN'/
&MATL ID='SCREEN',DENSITY=2700.,CONDUCTIVITY=200,SPECIFIC_HEAT=0.9/
&PART DRAG_LAW='SCREEN',ID='SCREEN1',SURF_ID='SCREEN',FREE_AREA_FRACTION=0.7, STATIC=.TRUE.,ORIENTATION=1,0,0 /
&PART DRAG_LAW='SCREEN',ID='SCREEN2',SURF_ID='SCREEN',FREE_AREA_FRACTION=0.7, STATIC=.TRUE.,ORIENTATION=1,0,0 /
&INIT N_PARTICLES_PER_CELL=1,CELL_CENTERED=.TRUE.,PART_ID='SCREEN1',XB=1.05,1.05,0.0,1.0,0.0,1.0/
&INIT N_PARTICLES_PER_CELL=1,CELL_CENTERED=.TRUE.,PART_ID='SCREEN2',XB=1.00,1.00,0.0,1.0,1.1,2.1/
&TAIL /
```

When the particles fall at the edge of grid  cell, they induce a fictitious velocity.

**Comment by Petr88** [comment]
I see, so I can tell, that it is not problem. It is just a fictitious value, which is shown only in SMV? Right?

**Comment by mcgratta** [comment]
No, it is a real problem. There should be no velocity induced by the screen.

**Comment by Petr88** [comment]
Ok so i cannot use screen at the edge of grid cell, if i want to preclude this velocity? I have to use functional location of screen as you have in your case.

**Comment by mcgratta** [comment]
Yes, that is a good work-around for now. We should fix the bug, however.

**Comment by Petr88** [comment]
Thanks a lot for you help :)

**Comment by mcgratta** [comment]
I tested the case above with

```
Revision         : Git-r5-398-gc6b7a08
Revision Date    : Fri Dec 18 09:11:29 2015 -0500
Compilation Date : Dec 18, 2015  09:20:41
```

and things appear to work correctly. 

Petr -- continue to use the work around until the next release.

**Comment by LauraEB** [comment]
![wcp5_0004](https://cloud.githubusercontent.com/assets/18728852/14905297/af494516-0df2-11e6-82ec-af751bb7d2fa.png)
Hi There, 

I am still having this problem on 6.4.0.
I tried to adjust the placement of my particles as suggested but cannot see any particles on an 'edge' and am still getting the strange velocities. 
When I moved to 6.4.0 I was getting some numerical instabilities with the max velocity error located in areas that did not appear to have anything strange happening (i.e. near the roof a few meters from a mesh boundary). I tried using a large MAX_DRAG_CFL as suggested in another thread and the model is running through however the velocities are still appearing. They now seem to be appearing later in 6.4.0  (~30s) than in 6.3.2 (~3-6s). 

Unfortunately the model that this is happening to is very large so it's probably no good to upload it. Let me know if there is more evidence I can send through to help
![wcp14](https://cloud.githubusercontent.com/assets/18728852/14905273/79a09a4a-0df2-11e6-9f53-56851c1f6f31.PNG)

Any advice would be greatly appreciated.
![wcp3_0003](https://cloud.githubusercontent.com/assets/18728852/14905192/c9cf5e94-0df1-11e6-86d2-5c7ef15a90bf.png)

Thanks
Laura
...

**Comment by mcgratta** [comment]
Whenever I have a problem with some aspect of FDS, I create a very simple, small test case to work the issue. If you continue running this giant case, you will get more and more frustrated. Create a small test case that exhibits the problem and then we can help you solve it. You are doing something that is not commonly done with FDS, so we have to see if the algorithm we implemented is appropriate for your case.

**Comment by drjfloyd** [comment]
Looking at the velocity vector image, it looks like you have screens that are offset by one grid cell. Are there hidden obstructions between those screens or is there a one cell thick gas gap between them? If there is a gap, it is possible that might be causing problems.

**Comment by LauraEB** [comment]
Hi, 
drjfloyd: yes there are hidden obstructions, sorry they don't show up as it's a clip through the geometry.

mcgratta: Frustrated is correct!!
Here is my small test case:
It still has the 3 car fire which has a lot of controls so it seems a bit long sorry. I wondered if initial conditions (say a low velocity) might help?

Thanks for your Help

`
&HEAD CHID='WCPtester2'/
&TIME T_END=3600.0, DT=0.25/
&DUMP RENDER_FILE='WCPtester2.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_PL3D=60.0, DT_RESTART=300.0, DT_SLCF=3.0, PLOT3D_QUANTITY='PRESSURE','U-VELOCITY','V-VELOCITY','W-VELOCITY','VISIBILITY'/
&MISC DRAG_CFL_MAX=100000/

&MESH ID='Mesh01', IJK=120,120,40, XB=138.0,162.0,-8.0,16.0,0.0,8.0/
&MESH ID='Mesh02', IJK=120,120,40, XB=138.0,162.0,16.0,40.0,0.0,8.0/
&MESH ID='Mesh03', IJK=120,120,40, XB=138.0,162.0,40.0,64.0,0.0,8.0/

&PART ID='SCREEN2',
      STATIC=.TRUE.,
      SURF_ID='SURFSCREEN2',
      DRAG_LAW='SCREEN',
      ORIENTATION(1,1)=0.0, ORIENTATION(2,1)=1.0, ORIENTATION(3,1)=0.0,
      FREE_AREA_FRACTION=0.4/
&PART ID='SCREEN3',
      STATIC=.TRUE.,
      SURF_ID='SURFSCREEN3',
      DRAG_LAW='SCREEN',
      ORIENTATION(1,1)=0.0, ORIENTATION(2,1)=1.0, ORIENTATION(3,1)=0.0,
      FREE_AREA_FRACTION=0.32/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1/

&DEVC ID='TIMER', QUANTITY='TIME', XYZ=138.0,-8.0,0.0, SETPOINT=1380.0/
&DEVC ID='TIMER2', QUANTITY='TIME', XYZ=138.0,-8.0,0.0, SETPOINT=720.0/
&DEVC ID='TIMER3', QUANTITY='TIME', XYZ=138.0,-8.0,0.0, SETPOINT=2100.0/
&MATL ID='ALUMINUM',
      SPECIFIC_HEAT=0.9,
      CONDUCTIVITY=200.0,
      DENSITY=2700.0/
&MATL ID='STEEL',
      FYI='Drysdale, Intro to Fire Dynamics - ATF NIST Multi-Floor Validation',
      SPECIFIC_HEAT=0.46,
      CONDUCTIVITY=45.8,
      DENSITY=7850.0,
      EMISSIVITY=0.95/
&MATL ID='CONCRETE',
      FYI='NBSIR 88-3752 - ATF NIST Multi-Floor Validation',
      SPECIFIC_HEAT=1.04,
      CONDUCTIVITY=1.8,
      DENSITY=2280.0/

&SURF ID='SURFSCREEN2',
      MATL_ID(1,1)='ALUMINUM',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=8.0E-4/
&SURF ID='SURFSCREEN3',
      MATL_ID(1,1)='ALUMINUM',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=9.0E-4/
&SURF ID='steelscreen',
      RGB=146.0,104.0,249.0,
      BACKING='VOID',
      MATL_ID(1,1)='STEEL',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.01/
&SURF ID='Concrete',
      RGB=146.0,202.0,166.0,
      BACKING='VOID',
      MATL_ID(1,1)='CONCRETE',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.4/
&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./
&SURF ID='CAR_FIRE_ENGINE',
      COLOR='RED',
      HRRPUA=1017.0,
      RAMP_Q='CAR_FIRE_ENGINE_RAMP_Q'/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=0.0, F=0.0/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=240.0, F=0.3936/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=960.0, F=0.3936/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=1440.0, F=0.6627/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=1500.0, F=1.0/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=1620.0, F=0.5422/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=1680.0, F=0.5038/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=2160.0, F=0.1972/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=2220.0, F=0.1588/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=2280.0, F=0.1205/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=2340.0, F=0.1167/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=3000.0, F=0.0753/
&RAMP ID='CAR_FIRE_ENGINE_RAMP_Q', T=4200.0, F=0.0/
&SURF ID='CAR_FIRE_CAB',
      COLOR='RED',
      HRRPUA=1017.0,
      RAMP_Q='CAR_FIRE_CAB_RAMP_Q'/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=0.0, F=0.0/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=60.0, F=0.667/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=120.0, F=1.0/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=240.0, F=0.5422/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=300.0, F=0.5038/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=780.0, F=0.1972/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=840.0, F=0.1588/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=900.0, F=0.1205/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=960.0, F=0.1167/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=1620.0, F=0.0753/
&RAMP ID='CAR_FIRE_CAB_RAMP_Q', T=2820.0, F=0.0/

&INIT ID='SCREEN2', PART_ID='SCREEN2', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=148.4,155.3,-3.7,-3.7,1.25,5.35/
&INIT ID='SCREEN2', PART_ID='SCREEN2', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=136.8,143.7,-3.7,-3.7,1.25,5.35/
&INIT ID='SCREEN3', PART_ID='SCREEN3', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=143.8,148.4,-2.65,-2.65,1.25,5.35/
&INIT ID='SCREEN3', PART_ID='SCREEN3', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=155.4,163.9,-2.65,-2.65,1.25,5.35/

&OBST XB=136.8,137.0,-3.6,-2.6,0.0,6.0, SURF_ID='steelscreen'/ 0.4 side
&OBST XB=143.6,143.8,-3.6,-2.6,0.0,6.0, SURF_ID='steelscreen'/ 0.4 side
&OBST XB=148.4,148.6,-3.6,-2.6,0.0,6.0, SURF_ID='steelscreen'/ 0.4 side
&OBST XB=155.2,155.4,-3.6,-2.6,0.0,6.0, SURF_ID='steelscreen'/ 0.4 side
&OBST XB=164.0,164.2,-3.6,-2.6,0.0,6.0, SURF_ID='steelscreen'/ 0.4 side
&OBST XB=160.462,219.333,57.2,64.6,5.4,6.0, SURF_ID='Concrete'/ roof
&OBST XB=119.6,159.4,-2.8,17.4,5.4,6.0, SURF_ID='Concrete'/ roof
&OBST XB=119.6,159.4,17.4,29.4,5.4,6.2, SURF_ID='Concrete'/ roof
&OBST XB=119.6,159.4,-2.8,-2.8,5.4,5.6, SURF_ID='Concrete'/ roof
&OBST XB=119.6,159.4,29.4,37.8,5.4,6.2, SURF_ID='Concrete'/ roof
&OBST XB=119.6,159.4,37.8,58.0,5.4,6.4, SURF_ID='Concrete'/ roof
&OBST XB=159.4,199.2,-2.8,17.4,5.4,6.0, SURF_ID='Concrete'/ roof
&OBST XB=159.4,199.2,17.4,29.4,5.4,6.2, SURF_ID='Concrete'/ roof
&OBST XB=159.4,199.2,-2.8,-2.8,5.4,5.6, SURF_ID='Concrete'/ roof
&OBST XB=159.4,199.2,29.4,37.8,5.4,6.2, SURF_ID='Concrete'/ roof
&OBST XB=159.4,199.2,37.8,58.0,5.4,6.4, SURF_ID='Concrete'/ roof
&OBST XB=146.4,148.381,23.4,27.0576,0.8,1.1048, COLOR='BLACK', SURF_ID='ADIABATIC'/ Car2C
&OBST XB=148.99,150.972,23.4,27.0576,0.8,1.1048, COLOR='BLACK', SURF_ID='ADIABATIC'/ Car1C
&OBST XB=148.99,150.972,24.6192,26.448,1.7144,2.324, SURF_ID='ADIABATIC'/ Car1B
&OBST XB=148.99,150.972,23.4,27.0576,1.1048,1.7144, SURF_ID='ADIABATIC'/ Car1A
&OBST XB=146.4,148.381,24.6192,26.448,1.7144,2.324, SURF_ID='ADIABATIC'/ Car2B
&OBST XB=146.4,148.381,23.4,27.0576,1.1048,1.7144, SURF_ID='ADIABATIC'/ Car2A
&OBST XB=137.884,162.268,15.8194,37.4602,0.8,0.8, COLOR='GRAY 94', SURF_ID='ADIABATIC'/ Deck
&OBST XB=151.581,153.562,24.6192,26.448,1.7144,2.324, SURF_ID='ADIABATIC'/ Car3B
&OBST XB=151.581,153.562,23.4,27.0576,0.8,1.1048, COLOR='BLACK', SURF_ID='ADIABATIC'/ Car3C
&OBST XB=151.581,153.562,23.4,27.0576,1.1048,1.7144, SURF_ID='ADIABATIC'/ Car3A
&OBST XB=119.6,159.4,25.6,29.4,0.0,0.6, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,14.2,25.6,0.0,0.8, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,2.8,14.2,0.0,1.0, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,-2.8,2.8,0.0,1.2, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,48.2,59.6,0.0,0.2, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,36.8,48.2,0.0,0.4, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,29.4,36.8,0.0,0.6, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,59.6,65.2,0.0,0.0, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,25.6,29.4,0.0,0.6, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,14.2,25.6,0.0,0.8, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,2.8,14.2,0.0,1.0, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,-2.8,2.8,0.0,1.2, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,48.2,59.6,0.0,0.2, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,36.8,48.2,0.0,0.4, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,29.4,36.8,0.0,0.6, SURF_ID='Concrete'/ slab
&OBST XB=159.4,199.2,59.6,65.2,0.0,0.0, SURF_ID='Concrete'/ slab
&OBST XB=119.6,159.4,62.4,69.4,0.0,6.0, SURF_ID='Concrete'/ Ext wall
&OBST XB=159.4,199.2,62.4,69.4,0.0,6.0, SURF_ID='Concrete'/ Ext wall
&OBST XB=189.4,199.2,58.6,62.4,0.0,6.0, SURF_ID='Concrete'/ Ext wall
&OBST XB=192.4,199.2,57.8,58.6,0.0,6.0, SURF_ID='Concrete'/ Ext wall

&VENT SURF_ID='OPEN', XB=138.0,162.0,-8.0,-8.0,0.0,8.0/ Mesh Vent: Mesh01 [YMIN]
&VENT SURF_ID='OPEN', XB=138.0,162.0,-8.0,16.0,8.0,8.0/ Mesh Vent: Mesh01 [ZMAX]
&VENT SURF_ID='OPEN', XB=138.0,162.0,-8.0,-2.0,0.0,0.0/ Mesh Vent: Mesh01 [ZMIN]
&VENT SURF_ID='OPEN', XB=138.0,162.0,16.0,40.0,8.0,8.0/ Mesh Vent: Mesh02 [ZMAX]
&VENT SURF_ID='OPEN', XB=138.0,162.0,64.0,64.0,0.0,8.0/ Mesh Vent: Mesh03 [YMAX]
&VENT SURF_ID='OPEN', XB=138.0,162.0,40.0,64.0,8.0,8.0/ Mesh Vent: Mesh03 [ZMAX]
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=148.99,150.972,23.4,24.6192,1.7144,1.7144, IOR=3/ c1-f1
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=148.99,150.972,23.4,23.4,1.1048,1.7144, IOR=-2/ c1-f2
&VENT SURF_ID='CAR_FIRE_CAB', XB=148.99,150.972,24.6192,24.6192,1.7144,2.324, IOR=-2, DEVC_ID='TIMER'/ c1-f3
&VENT SURF_ID='CAR_FIRE_CAB', XB=148.99,150.972,26.448,26.448,1.7144,2.324, IOR=2, DEVC_ID='TIMER'/ c1-f4
&VENT SURF_ID='CAR_FIRE_CAB', XB=148.99,148.99,24.6192,26.448,1.7144,2.324, IOR=-1, DEVC_ID='TIMER'/ c1-f5
&VENT SURF_ID='CAR_FIRE_CAB', XB=150.972,150.972,24.6192,26.448,1.7144,2.324, IOR=1, DEVC_ID='TIMER'/ c1-f6
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=146.4,148.381,23.4,24.6192,1.7144,1.7144, IOR=3, DEVC_ID='TIMER2'/ c2-f01
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=146.4,148.381,23.4,23.4,1.1048,1.7144, IOR=-2, DEVC_ID='TIMER2'/ c2-f02
&VENT SURF_ID='CAR_FIRE_CAB', XB=146.4,148.381,24.6192,24.6192,1.7144,2.324, IOR=-2, DEVC_ID='TIMER3'/ c2-f03
&VENT SURF_ID='CAR_FIRE_CAB', XB=146.4,148.381,26.448,26.448,1.7144,2.324, IOR=2, DEVC_ID='TIMER3'/ c2-f04
&VENT SURF_ID='CAR_FIRE_CAB', XB=146.4,146.4,24.6192,26.448,1.7144,2.324, IOR=-1, DEVC_ID='TIMER3'/ c2-f05
&VENT SURF_ID='CAR_FIRE_CAB', XB=148.381,148.381,24.6192,26.448,1.7144,2.324, IOR=1, DEVC_ID='TIMER3'/ c2-f06
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=151.581,153.562,23.4,24.6192,1.7144,1.7144, IOR=3, DEVC_ID='TIMER2'/ c3-f1
&VENT SURF_ID='CAR_FIRE_ENGINE', XB=151.581,153.562,23.4,23.4,1.1048,1.7144, IOR=-2, DEVC_ID='TIMER2'/ c3-f2
&VENT SURF_ID='CAR_FIRE_CAB', XB=151.581,153.562,24.6192,24.6192,1.7144,2.324, IOR=-2, DEVC_ID='TIMER3'/ c3-f3
&VENT SURF_ID='CAR_FIRE_CAB', XB=151.581,153.562,26.448,26.448,1.7144,2.324, IOR=2, DEVC_ID='TIMER3'/ c3-f4
&VENT SURF_ID='CAR_FIRE_CAB', XB=151.581,151.581,24.6192,26.448,1.7144,2.324, IOR=-1, DEVC_ID='TIMER3'/ c3-f5
&VENT SURF_ID='CAR_FIRE_CAB', XB=153.562,153.562,24.6192,26.448,1.7144,2.324, IOR=1, DEVC_ID='TIMER3'/ c3-f6

&TAIL /
`

**Comment by mcgratta** [comment]
Helpful hint when posting input files here. Add ``` (back quotes) before and after the text.

```
&VENT SURF_ID='CAR_FIRE_CAB', XB=151.581,151.581,24.6192,26.448,1.7144,2.324, IOR=-1, DEVC_ID='TIMER3'/ c3-f5
&VENT SURF_ID='CAR_FIRE_CAB', XB=153.562,153.562,24.6192,26.448,1.7144,2.324, IOR=1, DEVC_ID='TIMER3'/ c3-f6
```

**Comment by LauraEB** [comment]
Hi Guys, in relation to this problem. I have a question about the velocity referenced in equation 8.36 in the User guide: Is _u_  the approach velocity, the 'actual velocity' seen across the screen or it the approach velocity with some other reduction factor?
Thanks 
Laura

**Comment by drjfloyd** [comment]
It is the velocity in the cell containing the screen.
