### ISSUE TITLE
Model with sprinklers keeps crashing - need urgent help :(

### ISSUE THREAD

**Issue by cmpriscilla** [firemodels/fds#5454]
[LL6-08.txt](https://github.com/firemodels/fds/files/1302026/LL6-08.txt)

Hi,

We had a model with sprinklers activation which keeps crashing shortly after the sprinklers activated.
It looks like the interaction between the sprinklers and the fire source is the cause, but we have compared with other team's model with such interaction and survived the whole run.
We have tried multiple versions of this model, from deleting some columns, activating less sprinklers, shifting the fire location and mesh a little bit, but they all crashed.

The aim of this model is to get the radiation flux (boundary output) on the wall placed in the middle of the corridor just north of the fire.

Would someone please help advise what is wrong with the model?
We are currently trying out another version with fire suppression disabled.

Thank you!

Cheers,
Pris

**Comment by cmpriscilla** [comment]
Update: The new run with no fire suppression crashed, too.

**Comment by mcgratta** [comment]
What version of FDS are you using? When you say "no fire suppression", do you mean that the sprinklers have not activated? When does the calculation stop? Does it stop with a numerical instability? If so, where does it occur in the computational domain?

I suggest that if you cannot find the problem that you simplify the case. Remove the meshes and obstructions that are not involved. Try to make the case smaller and thus easier to debug.

**Comment by Er9y714** [comment]
If the same file runs in others' PCs as you stated, then it might be stopping due to insufficient memory in your PC when sprinkler particles are injected (sprinklers activate). Please check/watch your memory usage in task manager.

**Comment by rmcdermo** [comment]
I have the case running now.  At approximately what time does it crash?  Too hard to tell from input file when sprinklers comes on, looks like a temperature setting.

**Comment by rmcdermo** [comment]
@cmpriscilla Can you please tell approximately when this case should crash?

**Comment by cmpriscilla** [comment]
Hi, thank you so much for your help and sorry for the delayed answers.

They always crashed at about 10-30s after the sprinklers were activated, which in this particular case was within the first 60-90s. I'm sorry I'll need to check the exact time at work tomorrow. May I know how long has it been running on your side @rmcdermo ?

@mcgratta The version of fds used was 6.5.2 and we ran it on an MPI cluster.
By "no fire suppression" I meant I didn't let the sprinklers' water drops to reduce the fire source's HRR.

Update: We tried another version with only 2MW fire (instead of 4MW) and it survived longer than usual after the sprinklers had activated (it was at about 100-200s already). We decided to kill that 2MW run, though, because we needed the space urgently for runs with report-worthy results, so I'm not sure if it was going to finish running or crashed eventually.

**Comment by sbenkorichi** [comment]
When y say we tried another version. Which one was? 6.5.3?

**Comment by cmpriscilla** [comment]
@sbenkorichi Sorry I meant another scenario with 2MW fire (reducing the HRRPUA only, not the fire bed size). The fds used was version 6.5.2 throughout.

**Comment by sbenkorichi** [comment]
Ok. But we recommend using the latest version 6.5.3 as many bugs were fixed already. So it would be pointless to fix previous releases. Try installing the latest one and see if it gives you an error.

**Comment by rmcdermo** [comment]
Case has run up to 442 s with latest code.  I'm going to close this for now.  But let us know if you see any problems when using v6.5.3.

![ll6-08_0369](https://user-images.githubusercontent.com/4418497/30545639-3cf21a2e-9c58-11e7-8d74-219fb32c37b9.png)

**Comment by cmpriscilla** [comment]
Upgrading to 6.5.3 is not an easy option to take right now since it's sitting on a big cluster of remote PCs.
Right now we're reduced the number of water particles injected per second to just 500 and run separate cases of just the radiation output only and the typical slice files only, both still crashed.

Here is an example error message from the run with typical slice files results only.
@mcgratta @rmcdermo If you don't mind, could you please take a look at it and advise me what problems is it saying?

[LL6-12.txt](https://github.com/firemodels/fds/files/1316258/LL6-12.txt)
