### ISSUE TITLE
mpiexec problem FDS 6.7.0 #6575

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#6576]
Sorry, the simplifying went to fast - however the problem still occurs.

[tnl.txt](https://github.com/firemodels/fds/files/2152605/tnl.txt)
[cmd-output-FDS670.txt](https://github.com/firemodels/fds/files/2152606/cmd-output-FDS670.txt)
[cmd-output-FDS660.txt](https://github.com/firemodels/fds/files/2152607/cmd-output-FDS660.txt)

**Comment by sbenkorichi** [comment]
Right, I can see your problem. I'm not windows user, but I tested it on my laptop, with 6.6.0 it works, and it doesn't work with 6.7.0. My colleagues have better knowledge on Windows and they will advise you.

Running it with fds only works, and it fails even with single mpi process. We'll take a look at this.

```
mpiexec -np 1 fds tnl.fds
[unset]: Error reading initack on 656
Error on readline:: No error
[unset]: write_line error; fd=656 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=656 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=656 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=656 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
```

**Edit:**
Works fine under Linux.

**Comment by mcgratta** [comment]
It works for me on a Windows 10 laptop. Check your installation by typing
```
where mpiexec
```
Tell me what your computer says.

**Comment by sbenkorichi** [comment]
here,
mine is Windows 10 as well.
```
where mpiexec
c:\Program Files\firemodels\FDS6\bin\mpiexec.exe
```

**Comment by fidran** [comment]
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\CFD\TNL-670>where mpiexec
c:\Program Files\firemodels\FDS6\bin\mpiexec.exe

C:\CFD\TNL-670>

**Comment by mcgratta** [comment]
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\mcgratta>where mpiexec
c:\Program Files\firemodels\FDS6\bin\mpiexec.exe
```

Now do this:
```
mpiexec -n 4 test_mpi
```

**Comment by sbenkorichi** [comment]
```
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.
```


```
C:\Users\SBenkorichi>mpiexec -n 4 test_mpi
[unset]: Error reading initack on 664
Error on readline:: No error
[unset]: write_line error; fd=664 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=664 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=664 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=664 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
[unset]: Error reading initack on 660
Error on readline:: No error
[unset]: write_line error; fd=660 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: Error reading initack on 648
[unset]: write_line error; fd=660 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=660 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Error on readline:: No error
[unset]: write_line error; fd=648 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=648 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=648 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=660 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=648 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
[unset]: Error reading initack on 148
Error on readline:: No error
[unset]: write_line error; fd=148 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=148 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=148 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=148 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
```

**Comment by f-tanaka0123** [comment]
I have the same problem as sbenkorichi.
In my case, FDS6.2.0 can run on windows10, but FDS6.5.3 or later version cannot run.

I guess that FDS developer faced the same problem in the function call MPI_FILE_SET_VIEW when Intel Fortran was updated from Version 16 to 17.
Does Intel MPI developer claim that the problem in Intel MPI was resolved completely?

**Comment by rmcdermo** [comment]
@SusanKilian Please acknowledge that you see this was assigned to you.  Thanks.

**Comment by mcgratta** [comment]
I cannot reproduce this error.

**Comment by sbenkorichi** [comment]
Installed fds6.7 on my colleague's desktop machine, it has the absolute same build of windows 10. Yet on his it works with mpi, and on my laptop it fails.

**Comment by bphusted** [comment]
I have the same problem on my windows 7 machine using mpiexec. 

C:\Users\bran-bpa>mpiexec -np 4 test_mpi.exe
[unset]: Error reading initack on 452
Error on readline:: No error
[unset]: write_line error; fd=452 buf=:cmd=init pmi_version=1 pmi_subversion=1

I have tried to uninstall and install hydra_service  several times using different version of intel mpi, but the problem is still there. I also have the same problem on a windows 10 machine.

**Comment by mcgratta** [comment]
Type this at the command prompt:
```
where mpiexec
```
This will indicate which `mpiexec` you are using. You want the one in FDS6\bin to be listed first.

**Comment by bphusted** [comment]
Typing "where mpiexe" gives 
d:\firemodels\FDS6\bin\mpiexec.exe which is the same place as the fds.exe file. The same for "where hydra_service"  
I have removed all other paths to mpiexec.exe and hydra_service in the path file in environmental variables. I have a number of other programs installed on the pc, which uses mpi (matlab and comsol, and also the Intel Parallel Studio XE 2018).

**Comment by mcgratta** [comment]
I sometimes have this kind of problem because I also have Intel PS installed, which can conflict with the latest FDS "official" installation. My suggestion is to compile the code yourself and not use the FDS download if you have the compiler.

**Comment by sbenkorichi** [comment]
As much dumb this might sound, this is what I did. 
I unzipped fds6.6 in my desktop, then I copied the `mpiexec.exe` and the `mpi_proxy.exe`,` impi.dll`, `libiomp5md.dll`, `hydra_service2.exe` of` fds6.6\bin` into `c:\Program Files\firemodels\FDS6\bin\` FDS runs now in parallel on my laptop, although this is not a fix for this problem.
Is there any other ideas to try?

**Comment by Er9y714** [comment]
Why is `hydra_service2.exe` named with "`2`"? Is it normal?

**Comment by mcgratta** [comment]
We plan to do a maintenance release soon. We'll bundle with the latest version of the libs. I would not recommend to others to do what you have done because it is too risky to mix and match libs.

**Comment by sbenkorichi** [comment]
Well, I've got the same compiler as the one was used for the release (18.2). Here is some infos
```
where mpiexec
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.2.185\windows\mpi\intel64\bin\mpiexec.exe
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt\mpiexec.exe
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt\mpiexec.exe
```
```
mpiexec --version
Intel(R) MPI Library for Windows* OS, Version 2018 Update 2 Build 20180125
Copyright 2003-2018 Intel Corporation.
```
Compiled fds fine ( I used the same source of the latest release). However, when running simple cases, I still receive the same error. 

```
mpiexec -np 2 -localonly fds_impi_win_64.exe device_test.fds
[unset]: Error reading initack on 720
Error on readline:: No error
[unset]: write_line error; fd=720 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=720 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=720 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=720 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
[unset]: Error reading initack on 660
Error on readline:: No error
[unset]: write_line error; fd=660 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=660 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=660 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=660 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
```

I tried to do a dummy echo hello world and worked fine.
```
@ECHO OFF
mpiexec -np 4 -localonly echo Hello, World !
Hello, World !
Hello, World !
Hello, World !
Hello, World !
ECHO ON
```
I don't understand why it's giving this behavior.

**Comment by Er9y714** [comment]
@sbenkorichi 
`where `query returns three outputs. In that case which one is executed when it is called? Is having multiple defined paths and files healthy?

**Comment by mcgratta** [comment]
The first one listed is the one that is run.

**Comment by ankit171032** [comment]
I am also waiting for the solution to this problem. So commenting here to get the update as soon as some one will resolve it.

**Comment by stragest** [comment]
So I have tried getting this to work on 4 separate computers (Win7, 3 laptops and 1 desktop, different models) and have had mixed results. Originally I couldn't get mpi to work on any of them, but after removing all versions of pyrosim, including the latest, I was able to get two working while the other two are getting the same error as everyone else.

I have checked the environmental variables on all four, but I have not seen any similarities between those that work and those that don't. I also tried moving the intel mpi files to a different location and got the same results so I do not believe the mpi file path is the issue. There has to be another conflict somewhere, but I have no idea what it could be. I attached the error message below for reference.

![image](https://user-images.githubusercontent.com/43825884/46431229-41fcda80-c719-11e8-8e36-56decd1b0a7e.png)

**Comment by stragest** [comment]
> So I have tried getting this to work on 4 separate computers (Win7, 3 laptops and 1 desktop, different models) and have had mixed results. Originally I couldn't get mpi to work on any of them, but after removing all versions of pyrosim, including the latest, I was able to get two working while the other two are getting the same error as everyone else.
> 
> I have checked the environmental variables on all four, but I have not seen any similarities between those that work and those that don't. I also tried moving the intel mpi files to a different location and got the same results so I do not believe the mpi file path is the issue. There has to be another conflict somewhere, but I have no idea what it could be. I attached the error message below for reference.
> 
> ![image](https://user-images.githubusercontent.com/43825884/46431229-41fcda80-c719-11e8-8e36-56decd1b0a7e.png)

Update, I removed the intel compiler folder and environmental variable and now it works! 

![image](https://user-images.githubusercontent.com/43825884/46431905-fd723e80-c71a-11e8-9199-6cd0ad7c9a2f.png)

**Comment by mcgratta** [comment]
What do you mean by "the intel compiler folder"? Does this mean that you have installed the Intel Fortran or C compiler on your computer?

**Comment by Hindborg** [comment]
I'm getting the same error:
"[unset]: Error reading initack on 720
Error on readline:: No error
[unset]: write_line error; fd=720 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=720 buf=:cmd=barrier_in
...
...
..."
(the number 720 varies)

Both when running using the command
mpiexec -n 4 fds job_name.fds   (with my own file name of course)
and the command
mpiexec -hosts 1 m1 2 -wdir \\...\... fds job_name.fds   (with my own host name and file name of course)

The problem only occurs on computers that have had a previous version of FDS installed. Even when running the uninstall bat-file of the previous FDS-version before installing. And this is the case with both OS Windows 7 and OS Windows 10.
On our new computers (OS Windows 10), which haven't had any previous versions of FDS installed, FDS 6.7.0 runs just fine.

**Comment by mcgratta** [comment]
We are having similar problems. I don't know what to tell you. We're testing Intel 19 compilers and MPI, but having even more issues.

**Comment by mcgratta** [comment]
Open up the Task Manager, Services, and search for anything involving Intel hydra. The hydra_service controls the process to process communication. Make sure only one is running, otherwise, there will be a conflict. I find that I have to remove multiple versions of FDS which might have multiple versions of the hydra_service. Also, I find that adding -localonly to the mpiexec command helps if you are only running multiple MPI processes on a single machine.

**Comment by Hindborg** [comment]
Alright. Since nobody had mentioned old FDS-installations in the thread, I just wanted to make sure I hadn't stumpled upon something helpful.

I tried looking for Intel Hydra in the Task Manager, but could only find it once. And FDS isn't running with nor without out it.
Adding -localonly, sadly, didn't change anything either.

**Comment by mcgratta** [comment]
Try doing an uninstall of FDS, and then reinstall. That's all I can think of doing.

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by sbenkorichi** [comment]
Not really, I'm still not able to get it working.
I tried to clean all hydra etc and reinstall as fresh but still having the same problem.
It's just a black box not sure how to get around it. fds6.6 runs fine but starting with fds6.7 MPI process fails to run.

**Comment by sbenkorichi** [comment]
This ticket can be closed. Refer to https://github.com/firemodels/fds/issues/6756
Try the latest release and if there is an issue report back.
